[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
# optional, but helps:
combine_as_imports = true
force_single_line = false

[tool.pytest.ini_options]
testpaths = ['tests']

